# Generated by Django 2.2.2 on 2019-06-30 16:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris_synoptic", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="synopticgroup",
            name="fresh_time_limit",
            field=models.DurationField(
                default=datetime.timedelta(seconds=3600),
                help_text=(
                    "Maximum time that may have elapsed for the data to be "
                    "considered fresh. For data older than this the date on the map "
                    "shows red; for fresh data it shows green."
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="synoptictimeseries",
            name="title",
            field=models.CharField(
                blank=True,
                help_text=(
                    "Used as the chart title and as the time series title in the "
                    "report. Time series in different stations with the same title "
                    "will show as a layer on the map. Leave empty to use the time "
                    "series name."
                ),
                max_length=50,
            ),
        ),
    ]
