# Generated by Django 2.2.2 on 2019-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris_synoptic", "0002_add_fresh_time_limit")]

    operations = [
        migrations.AlterField(
            model_name="synopticgroup",
            name="fresh_time_limit",
            field=models.DurationField(
                help_text=(
                    "Maximum time that may have elapsed for the data to be "
                    "considered fresh. For data older than this the date on the map "
                    "shows red; for fresh data it shows green. Specify it in seconds "
                    "or in the format 'DD HH:MM:SS'."
                )
            ),
        )
    ]
