# Generated by Django 2.2.4.dev20190704113610 on 2019-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("enhydris_synoptic", "0003_change_fresh_time_limit")]

    operations = [
        migrations.AddField(
            model_name="synoptictimeseries",
            name="high_limit",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "If the variable goes higher than this, it will be shown red on "
                    "the map."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="synoptictimeseries",
            name="low_limit",
            field=models.FloatField(
                blank=True,
                help_text=(
                    "If the variable goes lower than this, it will be shown red on "
                    "the map."
                ),
                null=True,
            ),
        ),
    ]
