# Generated by Django 2.2.17 on 2020-12-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_synoptic", "0101_squashed"),
    ]

    operations = [
        migrations.CreateModel(
            name="EarlyWarningEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "synoptic_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enhydris_synoptic.SynopticGroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email address to send early warnings",
                "verbose_name_plural": "Where to send early warnings",
            },
        ),
    ]
