# Generated by Django 2.2.17 on 2021-02-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enhydris_synoptic", "0102_earlywarningemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="synoptictimeseriesgroup",
            name="symmetric_rocc",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "If this is selected, it is the absolute value of the change that "
                    "matters, not its direction. In this case, the allowed differences "
                    "must all be positive. If it's not selected, only rates larger "
                    "than a positive or smaller than a negative difference are "
                    "considered."
                ),
                verbose_name="Symmetric",
            ),
        ),
        migrations.CreateModel(
            name="RateOfChangeThreshold",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta_t", models.CharField(max_length=6)),
                ("allowed_diff", models.FloatField()),
                (
                    "synoptic_timeseries_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="enhydris_synoptic.SynopticTimeseriesGroup",
                    ),
                ),
            ],
        ),
    ]
