# Generated by Django 3.2.19 on 2023-05-25 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enhydris', '0116_alter_timeseriesgroup_gentity'),
        ('enhydris_synoptic', '0201_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synopticgroupstation',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enhydris.station'),
        ),
    ]
